"""dbt sync — generates dbt tests from DataVow contracts.

Transforms DataVow contract rules into dbt-native tests:
- Generic tests (schema.yml): not_null, unique, accepted_values
- Singular tests (SQL files): sql, row_count, range, regex

Generated tests run in ANY warehouse that dbt supports — Snowflake, BigQuery,
Redshift, SQL Server, PostgreSQL, DuckDB, etc.
"""

from __future__ import annotations

import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import yaml

from datavow.contract import DataContract, QualityRule, RuleType, Severity

# ──────────────────────────────────────────────
# Constants
# ──────────────────────────────────────────────

SYNC_DIR = "datavow"  # Subdirectory name for generated tests
HEADER = "-- Generated by DataVow — do not edit manually. Rerun: datavow dbt sync"
SCHEMA_HEADER = "# Generated by DataVow — do not edit manually. Rerun: datavow dbt sync"


# ──────────────────────────────────────────────
# SQL generators per rule type
# ──────────────────────────────────────────────


def _sql_for_not_null(model_name: str, rule: QualityRule) -> str | None:
    """not_null → handled as generic test in schema.yml, not a singular test."""
    return None


def _sql_for_unique(model_name: str, rule: QualityRule) -> str | None:
    """unique → handled as generic test in schema.yml, not a singular test."""
    return None


def _sql_for_accepted_values(model_name: str, rule: QualityRule) -> str | None:
    """accepted_values → handled as generic test in schema.yml, not a singular test."""
    return None


def _sql_for_sql(model_name: str, rule: QualityRule) -> str:
    """Custom SQL rule → singular test returning violating rows."""
    # The contract SQL uses SELECT COUNT(*) ... with a threshold.
    # We need to convert to SELECT * ... WHERE (violation condition).
    query = rule.query or ""
    # Replace {table} with dbt ref
    query = query.replace("{table}", f"{{{{ ref('{model_name}') }}}}")

    threshold = rule.threshold if rule.threshold is not None else 0

    if threshold == 0:
        # COUNT(*) > 0 means violations exist → wrap as: if count > 0, fail
        # But we need rows, not count. Try to extract WHERE clause.
        where_match = re.search(r"WHERE\s+(.+)$", query, re.IGNORECASE | re.DOTALL)
        if where_match:
            where_clause = where_match.group(1).strip()
            return f"SELECT *\nFROM {{{{ ref('{model_name}') }}}}\nWHERE {where_clause}"
        else:
            # Can't parse → wrap as count check
            return (
                f"-- Original query returns a count; test fails if count > {threshold}\n"
                f"WITH violations AS (\n"
                f"    {query}\n"
                f")\n"
                f"SELECT *\n"
                f"FROM violations\n"
                f"WHERE count > {threshold}"
            )
    else:
        # Threshold > 0: fail only if count exceeds threshold
        return (
            f"-- Threshold: {threshold} violations allowed\n"
            f"WITH violation_count AS (\n"
            f"    {query}\n"
            f")\n"
            f"SELECT *\n"
            f"FROM (SELECT ({query}) AS cnt)\n"
            f"WHERE cnt > {threshold}"
        )


def _sql_for_row_count(model_name: str, rule: QualityRule) -> str:
    """row_count → singular test checking total row count bounds."""
    conditions = []
    if rule.min is not None:
        conditions.append(f"cnt < {rule.min}")
    if rule.max is not None:
        conditions.append(f"cnt > {rule.max}")

    where = " OR ".join(conditions) if conditions else "FALSE"

    return (
        f"WITH row_check AS (\n"
        f"    SELECT COUNT(*) AS cnt\n"
        f"    FROM {{{{ ref('{model_name}') }}}}\n"
        f")\n"
        f"SELECT cnt\n"
        f"FROM row_check\n"
        f"WHERE {where}"
    )


def _sql_for_range(model_name: str, rule: QualityRule) -> str:
    """range → singular test returning rows outside range."""
    conditions = []
    if rule.min_value is not None:
        conditions.append(f'"{rule.field}" < {rule.min_value}')
    if rule.max_value is not None:
        conditions.append(f'"{rule.field}" > {rule.max_value}')

    where = " OR ".join(conditions) if conditions else "FALSE"

    return (
        f"SELECT *\n"
        f"FROM {{{{ ref('{model_name}') }}}}\n"
        f'WHERE "{rule.field}" IS NOT NULL\n'
        f"  AND ({where})"
    )


def _sql_for_regex(model_name: str, rule: QualityRule) -> str:
    """regex → singular test returning rows not matching pattern.

    Uses REGEXP_LIKE which is supported by most warehouses
    (Snowflake, BigQuery, Redshift, PostgreSQL, DuckDB).
    SQL Server uses LIKE patterns instead.
    """
    pattern = (rule.pattern or "").replace("'", "''")

    return (
        f"SELECT *\n"
        f"FROM {{{{ ref('{model_name}') }}}}\n"
        f'WHERE "{rule.field}" IS NOT NULL\n'
        f"  AND NOT REGEXP_LIKE(CAST(\"{rule.field}\" AS VARCHAR), '{pattern}')"
    )


_SINGULAR_GENERATORS = {
    RuleType.SQL: _sql_for_sql,
    RuleType.ROW_COUNT: _sql_for_row_count,
    RuleType.RANGE: _sql_for_range,
    RuleType.REGEX: _sql_for_regex,
}

_GENERIC_TYPES = {RuleType.NOT_NULL, RuleType.UNIQUE, RuleType.ACCEPTED_VALUES}


# ──────────────────────────────────────────────
# Schema.yml generation (generic tests)
# ──────────────────────────────────────────────


def _build_schema_yml(
    model_name: str,
    contract: DataContract,
) -> dict[str, Any]:
    """Build a dbt schema.yml structure with generic tests from the contract.

    Merges schema-level checks (required, unique, allowed_values) and
    quality rules (not_null, unique, accepted_values) into dbt generic tests.
    """
    columns: dict[str, dict[str, Any]] = {}

    # From schema fields
    for field in contract.schema_.fields:
        col: dict[str, Any] = {"name": field.name}
        if field.description:
            col["description"] = field.description
        tests: list[Any] = []

        if field.required:
            tests.append({"not_null": {"tags": ["datavow"], "severity": "error"}})
        if field.unique:
            tests.append({"unique": {"tags": ["datavow"], "severity": "error"}})
        if field.allowed_values:
            tests.append(
                {
                    "accepted_values": {
                        "values": field.allowed_values,
                        "tags": ["datavow"],
                        "severity": "warn",
                    }
                }
            )

        if tests:
            col["data_tests"] = tests
        columns[field.name] = col

    # From quality rules (generic types only)
    for rule in contract.quality.rules:
        if rule.type not in _GENERIC_TYPES:
            continue

        col_name = rule.field
        if not col_name:
            continue

        if col_name not in columns:
            columns[col_name] = {"name": col_name}

        if "data_tests" not in columns[col_name]:
            columns[col_name]["data_tests"] = []

        severity = "error" if rule.severity == Severity.CRITICAL else "warn"

        if rule.type == RuleType.NOT_NULL:
            # Check if not_null already added from schema
            existing = [
                t
                for t in columns[col_name]["data_tests"]
                if isinstance(t, dict) and "not_null" in t
            ]
            if not existing:
                columns[col_name]["data_tests"].append(
                    {"not_null": {"tags": ["datavow"], "severity": severity}}
                )

        elif rule.type == RuleType.UNIQUE:
            existing = [
                t for t in columns[col_name]["data_tests"] if isinstance(t, dict) and "unique" in t
            ]
            if not existing:
                columns[col_name]["data_tests"].append(
                    {"unique": {"tags": ["datavow"], "severity": severity}}
                )

        elif rule.type == RuleType.ACCEPTED_VALUES and rule.values:
            existing = [
                t
                for t in columns[col_name]["data_tests"]
                if isinstance(t, dict) and "accepted_values" in t
            ]
            if not existing:
                columns[col_name]["data_tests"].append(
                    {
                        "accepted_values": {
                            "values": rule.values,
                            "tags": ["datavow"],
                            "severity": severity,
                        }
                    }
                )

    model_entry: dict[str, Any] = {
        "name": model_name,
        "description": contract.metadata.description,
        "columns": list(columns.values()),
    }

    if contract.metadata.tags:
        model_entry["tags"] = contract.metadata.tags

    return {
        "version": 2,
        "models": [model_entry],
    }


# ──────────────────────────────────────────────
# Sync engine
# ──────────────────────────────────────────────


class SyncResult:
    """Result of a sync operation for one contract."""

    def __init__(self, contract_name: str):
        self.contract_name = contract_name
        self.singular_tests: list[str] = []  # paths of generated SQL files
        self.generic_test_count: int = 0
        self.schema_yml_path: str | None = None
        self.skipped_rules: list[str] = []


def sync_contract(
    contract_path: str | Path,
    dbt_project_dir: str | Path,
    model_name: str | None = None,
    tests_dir: str | None = None,
) -> SyncResult:
    """Generate dbt tests from a DataVow contract.

    Args:
        contract_path: Path to the DataVow contract YAML.
        dbt_project_dir: Root of the dbt project.
        model_name: dbt model name (default: contract metadata.name).
        tests_dir: Override tests directory (default: tests/datavow/).

    Returns:
        SyncResult with paths of generated files.
    """
    contract = DataContract.from_yaml(contract_path)
    model = model_name or contract.metadata.name
    dbt_root = Path(dbt_project_dir)
    result = SyncResult(contract_name=contract.metadata.name)

    # Resolve output directory
    if tests_dir:
        singular_dir = Path(tests_dir) / SYNC_DIR
    else:
        singular_dir = dbt_root / "tests" / SYNC_DIR

    singular_dir.mkdir(parents=True, exist_ok=True)

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    # 1. Generate singular SQL tests
    for rule in contract.quality.rules:
        if rule.type in _GENERIC_TYPES:
            continue

        generator = _SINGULAR_GENERATORS.get(rule.type)
        if not generator:
            result.skipped_rules.append(rule.name)
            continue

        sql_body = generator(model, rule)
        if sql_body is None:
            continue

        severity_tag = rule.severity.value.lower()
        test_name = f"{model}__{rule.name}"
        # Sanitize filename
        safe_name = re.sub(r"[^a-zA-Z0-9_]", "_", test_name)
        file_path = singular_dir / f"{safe_name}.sql"

        content = (
            f"{HEADER}\n"
            f"-- Contract: {contract.metadata.name} | Rule: {rule.name} | "
            f"Severity: {rule.severity.value}\n"
            f"-- Synced: {now}\n"
            f"-- Config: {{{{ config(tags=['datavow', '{severity_tag}'], "
            f"severity='{_dbt_severity(rule.severity)}') }}}}\n"
            f"\n"
            f"{sql_body}\n"
        )

        file_path.write_text(content)
        result.singular_tests.append(str(file_path))

    # 2. Generate schema.yml with generic tests
    schema_data = _build_schema_yml(model, contract)
    generic_count = sum(
        len(col.get("data_tests", [])) for col in schema_data["models"][0].get("columns", [])
    )
    result.generic_test_count = generic_count

    if generic_count > 0:
        # Write to models/ directory alongside the model, or tests/datavow/
        schema_dir = singular_dir
        schema_path = schema_dir / f"_{model}__datavow.yml"
        yaml_content = f"{SCHEMA_HEADER}\n# Synced: {now}\n\n"
        yaml_content += yaml.dump(
            schema_data, sort_keys=False, default_flow_style=False, allow_unicode=True
        )
        schema_path.write_text(yaml_content)
        result.schema_yml_path = str(schema_path)

    return result


def _dbt_severity(severity: Severity) -> str:
    """Map DataVow severity to dbt test severity."""
    if severity == Severity.CRITICAL:
        return "error"
    return "warn"


# ──────────────────────────────────────────────
# Batch sync
# ──────────────────────────────────────────────


def sync_all(
    contracts_dir: str | Path,
    dbt_project_dir: str | Path,
    model_names: dict[str, str] | None = None,
    tests_dir: str | None = None,
    clean: bool = False,
) -> list[SyncResult]:
    """Sync all contracts in a directory to dbt tests.

    Args:
        contracts_dir: Directory containing DataVow contract YAML files.
        dbt_project_dir: Root of the dbt project.
        model_names: Optional mapping of contract name → dbt model name.
        tests_dir: Override tests directory.
        clean: Remove existing datavow tests before syncing.

    Returns:
        List of SyncResult for each contract.
    """
    contracts_path = Path(contracts_dir)
    dbt_root = Path(dbt_project_dir)

    # Resolve tests dir
    target_dir = Path(tests_dir) / SYNC_DIR if tests_dir else dbt_root / "tests" / SYNC_DIR

    # Clean existing generated tests
    if clean and target_dir.exists():
        for f in target_dir.iterdir():
            if f.is_file():
                f.unlink()

    # Find all contracts (including subdirectories for domain structure)
    contract_files = sorted(p for p in contracts_path.rglob("*.yaml") if p.is_file()) + sorted(
        p for p in contracts_path.rglob("*.yml") if p.is_file() and not p.name.startswith("_")
    )

    results: list[SyncResult] = []
    seen_stems: set[str] = set()

    for contract_file in contract_files:
        if contract_file.stem in seen_stems:
            continue
        seen_stems.add(contract_file.stem)

        model_name = None
        if model_names:
            # Try contract metadata name after loading
            try:
                c = DataContract.from_yaml(contract_file)
                model_name = model_names.get(c.metadata.name)
            except Exception:
                pass

        try:
            result = sync_contract(
                contract_path=contract_file,
                dbt_project_dir=dbt_project_dir,
                model_name=model_name,
                tests_dir=tests_dir,
            )
            results.append(result)
        except Exception:
            # Skip invalid contracts silently in batch mode
            pass

    return results
